trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'DryWetMidi/*'
    - 'Docs/*'
    - 'Resources/CI/build-artifacts-docs.yaml'
    - 'Resources/Utilities/InlineTextImages/*'
    - 'README.md'

pr: none

pool:
  vmImage: 'windows-latest'

variables:
- group: DryWetMIDI-Common-Variables

name: $(TeamProject)_$(SourceBranchName)_BuildDocs_$(LibraryVersion)$(Rev:.r)

steps:
- task: PowerShell@2
  displayName: Generate obsolete API hints
  inputs:
    targetType: filePath
    filePath: '$(Build.SourcesDirectory)/Resources/Scripts/Generate obsolete API hints.ps1'

- task: DotNetCoreCLI@2
  displayName: Build project
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration)'
    projects: 'DryWetMidi/Melanchall.DryWetMidi.csproj'

- task: PowerShell@2
  displayName: Setup docs pages
  inputs:
    targetType: filePath
    filePath: '$(Build.SourcesDirectory)/Resources/Scripts/Setup docs.ps1'

- task: PowerShell@2
  displayName: Generate obsolete API section
  inputs:
    targetType: filePath
    filePath: '$(Build.SourcesDirectory)/Resources/Scripts/Generate obsolete API section.ps1'

- task: PowerShell@2
  displayName: Install docfx
  inputs:
    targetType: 'inline'
    script: choco install docfx -y --version $(DocFxVersion)
      
- task: PowerShell@2
  displayName: Build docs
  inputs:
    targetType: 'inline'
    script: docfx Docs/docfx.json

- task: DotNetCoreCLI@2
  displayName: Inline API images
  inputs:
    command: 'run'
    arguments: '--configuration $(BuildConfiguration) -- $(Build.SourcesDirectory)\Docs\_site 20'
    projects: 'Resources/Utilities/InlineTextImages/InlineTextImages/InlineTextImages.csproj'

- task: PublishPipelineArtifact@1
  displayName: Publish 'Docs' artifact
  inputs:
    targetPath: Docs\_site
    artifact: Docs

- task: PublishPipelineArtifact@1
  displayName: Publish 'LatestReleaseNotes' artifact
  inputs:
    targetPath: Docs\latest-release-notes.md
    artifact: LatestReleaseNotes