trigger:
  batch: true
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - 'Resources/Utilities/ExportGitHubStatistics/*'
    - 'Resources/CI/stat-github.yaml'

pr: none

schedules:
- cron: '0 0 * * *'
  displayName: Export GitHub repo statistics
  branches:
    include:
    - develop
  always: 'true'

pool:
  vmImage: 'windows-latest'

variables:
- group: DryWetMIDI-InfluxDB-Variables

name: $(TeamProject)_ExportGitHubStat_$(Rev:r)

steps:
- task: PowerShell@2
  displayName: Export GitHub repo info to InfluxDB Cloud
  inputs:
    targetType: 'inline'
    script: |
      $location = Get-Location
      Write-Host "Building ExportGitHubStatistics..."
      dotnet publish "Resources/Utilities/ExportGitHubStatistics/ExportGitHubStatistics.sln" -c Release -r win10-x64 -o "$location/ExportGitHubStatistics"
      Write-Host "Built."
      
      Write-Host "Exporting GitHub repo info..."
      $url = "$(InfluxDB.Url)"
      $token = "$(InfluxDB.WriteToken)"
      $organization = "$(InfluxDB.Organization)"
      $bucket = "$(InfluxDB.Bucket)"
      $measurement = "$(InfluxDB.Measurement.GitHub)"
      $gitHubPat = "$(GitHubPat)"
      Start-Process "ExportGitHubStatistics/ExportGitHubStatistics.exe" -ArgumentList """$url"" ""$token"" ""$organization"" ""$bucket"" ""$measurement"" ""$gitHubPat""" -Wait -NoNewWindow
      Write-Host "Exported."